-- Wanneer SQL server wordt gebruikt obv Docker met Docker volumes
-- wordt geen gebruik gemaakt van create database commando waarin database en log files worden gespecificeerd 
CREATE DATABASE [TestSourceDB2]
GO

ALTER DATABASE [TestSourceDB2] SET COMPATIBILITY_LEVEL = 130
GO
ALTER DATABASE [TestSourceDB2] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TestSourceDB2] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TestSourceDB2] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TestSourceDB2] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TestSourceDB2] SET ARITHABORT OFF 
GO
ALTER DATABASE [TestSourceDB2] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TestSourceDB2] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TestSourceDB2] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [TestSourceDB2] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TestSourceDB2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TestSourceDB2] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TestSourceDB2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TestSourceDB2] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TestSourceDB2] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TestSourceDB2] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TestSourceDB2] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TestSourceDB2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TestSourceDB2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TestSourceDB2] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TestSourceDB2] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TestSourceDB2] SET  READ_WRITE 
GO
ALTER DATABASE [TestSourceDB2] SET RECOVERY FULL 
GO
ALTER DATABASE [TestSourceDB2] SET  MULTI_USER 
GO
ALTER DATABASE [TestSourceDB2] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TestSourceDB2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TestSourceDB2] SET DELAYED_DURABILITY = DISABLED 
GO
USE [TestSourceDB2]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [TestSourceDB2]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [TestSourceDB2] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
